### ISSUE TITLE
hiding navigation?

### ISSUE THREAD

**Issue by LukaPitamic** [voila-dashboards/voila-vuetify#13]
Hello, great project, I love it. Is there an easy way to hide navigation? Or how is it possible to customize it. Maybe some css injection trick?

**Comment by mariobuikhuizen** [comment]
Thanks!

You can change the default template by copying the directory `[env]/share/jupyter/voila/templates/vuetify-default` to e.g. `/Users/mariobuikhuizen/Library/Jupyter/voila/templates/my_override`. You can find where Voila looks for templates by running `voila --template dummy`, find the dir that's in your home dir and use it instead of my example dir. 

Then edit `/Users/mariobuikhuizen/Library/Jupyter/voila/templates/my_override/nbconvert_templates/app.html` and use your template by running voila with `voila --template my_override bqplot_vuetify_example.ipynb`

**Comment by DohunLee** [comment]
This is such an amazing project for voila, really nice!

My programm runs with.
`voila --template vuetify-default Desktop/TEST.ipynb`

I have the same issue as @LukaPitamic in the beginning. When following your instructions ( @mariobuikhuizen ), I do find  `[env]/share/jupyter/voila/templates/default` but not "vuetify-default". The "default" one is also empty and changing its name does not break my command line for some reason.

Also when running  `voila --template dummy` it puts me to the beginning of my environment, which does not help my find the correct path to the default templates.

Is somebody able to help me understand how to change/create a custom template?

![grafik](https://user-images.githubusercontent.com/70583102/96451707-4751f280-1218-11eb-8133-2bdb60ba443a.png)
