### ISSUE TITLE
Textarea with solo style

### ISSUE THREAD

**Issue by guimillet** [voila-dashboards/voila-vuetify#51]
## Description

Textareas with solo style are incorrectly displayed with voila-vuetify, the width is too large:

![image](https://user-images.githubusercontent.com/3398881/136714608-57265627-439d-4844-a20b-8e0b7003d88b.png)

## Reproduce

```python
import ipyvuetify as v
solo1 = v.Textarea(solo=True, v_model='Solo')
solo2 = v.Textarea(solo=True, v_model='Solo')
tf1 = v.Textarea(v_model='Default')
tf2 = v.Textarea(v_model='Default')
v.Container(
    _metadata={'mount_id': 'content'},
    children=[
        v.Row(children=[solo1, solo2]),
        v.Row(children=[tf1, tf2])
    ]
)
```
Render with vuetify-base template.

## Expected behavior

In comparison, there is no issue in Jupyterlab or with voila lab template:

![image](https://user-images.githubusercontent.com/3398881/136714556-bca35c51-8b99-4283-aa8c-ce15c2e7a7e0.png)

## Context

- voila version 0.2.16
- Operating System and version: Ubuntu 20.04.3 LTS
- Browser and version: Chrome 94.0.4606.54

<details><summary>Troubleshoot Output</summary>
<pre>
        voila                     0.2.16             pyhd8ed1ab_0    conda-forge
        voila-vuetify             0.5.2              pyhd8ed1ab_0    conda-forge

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `voila` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

### If using JupyterLab
- JupyterLab version: 3.1.14

<details><summary>Installed Labextensions</summary>
<pre>
.../.local/share/jupyter/labextensions
        jupyter-vuetify v1.8.1 enabled OK

.../conda/share/jupyter/labextensions
        jupyter-vue v1.6.0 enabled OK
[...]
</pre>
</details>

**Comment by guimillet** [comment]
The problem also occurs with the `outlined` style:
![image](https://user-images.githubusercontent.com/3398881/141211575-bf380016-7bbe-418a-9213-854ebe5c7631.png)

The width of the `v-input__slot` section remains equal to that of the parent `v-input__control` whatever the padding of `v-input__slot`, hence the overflow (with the lab template, width+padding of `v-input__slot` = width of `v-input__control`).

Similar issue with a Container inside a Container.

Another issue, which may not be related, is that the scroll bar on the right is always present.

**Comment by ahmadpgh** [comment]
@guimillet Did you manage to resolve this issue? I have a very similar problem with having scrollbars on popup dialogs and off margins for them

**Comment by mariobuikhuizen** [comment]
Looks like the styles we remove because they were giving a lot of conflicts, aren't removed any more, because they are part of index.css in later versions of Voila. See: https://github.com/voila-dashboards/voila-vuetify/blob/c21ab33afdda6810d6799553b9922cfb8b38c14b/share/jupyter/nbconvert/templates/vuetify-base/util.js#L223 . 

I think it's also the cause for [#ipyvuetify/200](https://github.com/mariobuikhuizen/ipyvuetify/issues/200)

In the case of this issue, this rule is setting the wrong boxing model:
 ```css
*,
*::before,
*::after {
  box-sizing: unset;
}
```

Setting it to the correct boxing model in dev-tools restores the right rendering:
<img width="954" alt="Screenshot 2021-12-20 at 14 43 53" src="https://user-images.githubusercontent.com/46192475/146777147-1a55b88c-cbba-4ff7-871a-3f6d3ffdce6b.png">
